spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin@123
    url: jdbc:mysql://localhost:3306/productdb?allowPublicKeyRetrieval=true&useSSL=false

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true